Table Справочник.фитМВЗ [note: 'Справочник: МВЗ'] {
  ИмяПредопределенныхДанных Строка("256,Переменная") [null]
  Предопределенный Булево [null]
  Ссылка Справочник.фитМВЗ [pk]
  ПометкаУдаления Булево [null]
  Наименование Строка("100,Переменная") [not null]
  Код Строка("10,Переменная") [null]
  КодМВЗ Строка("10,Переменная") [not null]
  БЕ Справочник.фитБалансовыеЕдиницы [ref: - Справочник.фитБалансовыеЕдиницы.Ссылка , null, default: 'Справочник.фитБалансовыеЕдиницы.ПустаяСсылка']
  Ответственный Строка("100,Переменная") [null]
  ДействительноС Дата("Дата") [null, default: 'ТекущаяДатаСеанса()']
  ДействительноПо Дата("Дата") [null, default: 'ТекущаяДатаСеанса()']
  Устаревшее Булево [null]
}

Table Справочник.фитБалансовыеЕдиницы [note: 'Справочник: Балансовые единицы'] {
  Ссылка Справочник.фитБалансовыеЕдиницы [pk]
}